import type { EventItem } from "@/lib/types";

export const EVENTS: EventItem[] = [
  { dayNe: "२८", dayEn: "28", monNe: "चैत", monEn: "Mar", yr: "२०८२",
    titleNe: "जनचासो कार्यक्रम — बेसीशहर", titleEn: "Public listening — Besisahar",
    timeNe: "बिहान ७:००–९:००", timeEn: "7:00–9:00 AM",
    locNe: "सांसद सम्पर्क कार्यालय, बेसीशहर–३", locEn: "MP Liaison Office, Besisahar-3",
    kindNe: "सार्वजनिक", kindEn: "Open" },
  { dayNe: "०२", dayEn: "02", monNe: "वैशाख", monEn: "Apr", yr: "२०८३",
    titleNe: "दोर्दी उठान सिँचाइ स्थल निरीक्षण", titleEn: "Dordi lift irrigation site visit",
    timeNe: "बिहान १०:००", timeEn: "10:00 AM",
    locNe: "दोर्दी गाउँपालिका वडा–३", locEn: "Dordi Rural Muni. Ward-3",
    kindNe: "क्षेत्र भ्रमण", kindEn: "Field visit" },
  { dayNe: "०९", dayEn: "09", monNe: "वैशाख", monEn: "Apr", yr: "२०८३",
    titleNe: "कफी कृषक भेट — मध्यनेपाल", titleEn: "Coffee farmers meet — Madhya Nepal",
    timeNe: "दिउँसो २:००", timeEn: "2:00 PM",
    locNe: "मध्यनेपाल न.पा. वडा–५", locEn: "Madhya Nepal Muni. Ward-5",
    kindNe: "सेक्टर", kindEn: "Sector" },
  { dayNe: "१५", dayEn: "15", monNe: "वैशाख", monEn: "Apr", yr: "२०८३",
    titleNe: "विज्ञान–प्रविधि कोष विधेयक छलफल", titleEn: "Science-Tech Fund Bill discussion",
    timeNe: "बिहान ११:००", timeEn: "11:00 AM",
    locNe: "संघीय संसद, बबरमहल", locEn: "Federal Parliament, Babarmahal",
    kindNe: "सांसदीय", kindEn: "Parliamentary" },
  { dayNe: "२०", dayEn: "20", monNe: "वैशाख", monEn: "Apr", yr: "२०८३",
    titleNe: "घले गाउँ पर्यटन महोत्सव", titleEn: "Ghalegaun Tourism Festival",
    timeNe: "दिनभर", timeEn: "All day",
    locNe: "घले गाउँ, क्व्होलासोथार", locEn: "Ghalegaun, Kwholasothar",
    kindNe: "सांस्कृतिक", kindEn: "Cultural" },
];
