import type { Municipality } from "@/lib/types";

export const MUNICIPALITIES: Municipality[] = [
  { id: "besisahar", ne: "बेसीशहर नगरपालिका", en: "Besisahar Municipality", type: "नगरपालिका", typeEn: "Municipality", hq: true,
    pop: "३४,१२७", area: "१४४ वर्ग किमी", wards: 11,
    projNe: "१२ सक्रिय", projEn: "12 active", issueNe: "शहरी योजना, फोहोर व्यवस्थापन", issueEn: "Urban plan, solid waste",
    x: 310, y: 280 },
  { id: "sundarbazar", ne: "सुन्दरबजार नगरपालिका", en: "Sundarbazar Municipality", type: "नगरपालिका", typeEn: "Municipality",
    pop: "२६,४८८", area: "१८५ वर्ग किमी", wards: 12,
    projNe: "९ सक्रिय", projEn: "9 active", issueNe: "बजार विस्तार, सिंचाइ", issueEn: "Market expansion, irrigation",
    x: 245, y: 315 },
  { id: "madhyanepal", ne: "मध्यनेपाल नगरपालिका", en: "Madhya Nepal Municipality", type: "नगरपालिका", typeEn: "Municipality",
    pop: "३२,९१४", area: "२३७ वर्ग किमी", wards: 13,
    projNe: "११ सक्रिय", projEn: "11 active", issueNe: "सडक, कफी क्लस्टर", issueEn: "Roads, coffee cluster",
    x: 170, y: 340 },
  { id: "rainas", ne: "राइनास नगरपालिका", en: "Rainas Municipality", type: "नगरपालिका", typeEn: "Municipality",
    pop: "२४,१६९", area: "१६२ वर्ग किमी", wards: 10,
    projNe: "७ सक्रिय", projEn: "7 active", issueNe: "खानेपानी, विद्यालय", issueEn: "Water, schools",
    x: 200, y: 395 },
  { id: "marsyangdi", ne: "मर्स्याङ्दी गाउँपालिका", en: "Marsyangdi Rural Municipality", type: "गाउँपालिका", typeEn: "Rural Municipality",
    pop: "१६,७८४", area: "४५२ वर्ग किमी", wards: 8,
    projNe: "८ सक्रिय", projEn: "8 active", issueNe: "जलविद्युत्, पर्यटन", issueEn: "Hydro, tourism",
    x: 370, y: 180 },
  { id: "dordi", ne: "दोर्दी गाउँपालिका", en: "Dordi Rural Municipality", type: "गाउँपालिका", typeEn: "Rural Municipality",
    pop: "१९,५३२", area: "२८३ वर्ग किमी", wards: 7,
    projNe: "१० सक्रिय", projEn: "10 active", issueNe: "उठान सिंचाइ, सडक", issueEn: "Lift irrigation, roads",
    x: 415, y: 260 },
  { id: "dudhpokhari", ne: "दूधपोखरी गाउँपालिका", en: "Dudhpokhari Rural Municipality", type: "गाउँपालिका", typeEn: "Rural Municipality",
    pop: "१८,०९१", area: "३८१ वर्ग किमी", wards: 8,
    projNe: "६ सक्रिय", projEn: "6 active", issueNe: "हिमाली पर्यटन, जडिबुटी", issueEn: "High-altitude tourism, herbs",
    x: 465, y: 160 },
  { id: "kwholasothar", ne: "क्व्होलासोथार गाउँपालिका", en: "Kwholasothar Rural Municipality", type: "गाउँपालिका", typeEn: "Rural Municipality",
    pop: "१४,८६२", area: "३०६ वर्ग किमी", wards: 6,
    projNe: "५ सक्रिय", projEn: "5 active", issueNe: "सडक पहुँच, विद्यालय", issueEn: "Road access, schools",
    x: 120, y: 255 },
];
