import type { Priority } from "@/lib/types";

export const PRIORITIES: Priority[] = [
  {
    id: "hydro",
    numNe: "०१", numEn: "01",
    titleNe: "मर्स्याङ्दी–दोर्दी ऊर्जा करिडोर",
    titleEn: "Marsyangdi–Dordi Energy Corridor",
    descNe: "लमजुङका चार खोला प्रणालीलाई जोड्दै २६० मेगावाट क्षमताको लघु–मझौला जलविद्युत् समूह। स्थानीय सेयर स्वामित्व अनिवार्य।",
    descEn: "Clustering 260 MW of small–medium hydro across four river systems with mandatory local equity.",
    statusNe: "विधेयक मस्यौदामा", statusEn: "Bill drafting",
    progress: 28,
    tagNe: "ऊर्जा", tagEn: "Energy",
  },
  {
    id: "road",
    numNe: "०२", numEn: "02",
    titleNe: "बेसीसहर–मनास्लु पर्यटन मार्ग",
    titleEn: "Besisahar–Manaslu Tourism Corridor",
    descNe: "अन्नपूर्ण सर्किटको आधार शहरलाई दोर्दी र खुदी हुँदै पूरै काला पत्रे सडक। ४८ पुल, ७ वटा दृश्य विश्राम स्थल।",
    descEn: "Full-blacktop ring road linking the Annapurna Circuit base, 48 bridges and 7 scenic waypoints.",
    statusNe: "DPR मा", statusEn: "DPR stage",
    progress: 42,
    tagNe: "पूर्वाधार", tagEn: "Infrastructure",
  },
  {
    id: "agri",
    numNe: "०३", numEn: "03",
    titleNe: "उच्च–मूल्य कृषि र कफी क्लस्टर",
    titleEn: "High-value Agriculture & Coffee Cluster",
    descNe: "६,५०० हेक्टर पाखो जग्गामा कफी, अदुवा, अकबरे; साझा प्रशोधन केन्द्र र जैविक प्रमाणीकरण।",
    descEn: "6,500 ha of hill terraces into coffee, ginger & akbare with shared processing and organic cert.",
    statusNe: "पाइलट सुरु", statusEn: "Pilot active",
    progress: 61,
    tagNe: "कृषि", tagEn: "Agriculture",
  },
  {
    id: "digital",
    numNe: "०४", numEn: "04",
    titleNe: "डिजिटल लमजुङ — ग्रामीण फाइबर",
    titleEn: "Digital Lamjung — Rural Fibre",
    descNe: "सबै ८ स्थानीय तहका वडा केन्द्रसम्म फाइबर ब्रोडब्यान्ड, पालिका डाटा सेन्टर र सेवा एप।",
    descEn: "Fibre broadband to every ward center, palika data centers, and unified citizen services app.",
    statusNe: "टेन्डर तयारी", statusEn: "Pre-tender",
    progress: 18,
    tagNe: "प्रविधि", tagEn: "Technology",
  },
  {
    id: "water",
    numNe: "०५", numEn: "05",
    titleNe: "खानेपानी र सिँचाइ सुदृढीकरण",
    titleEn: "Water Supply & Irrigation",
    descNe: "१४३ बस्ती खानेपानी परियोजना, उठान सिँचाइ दोर्दी खण्ड; स्थानीय सञ्चालन समितिमा ५०% महिला।",
    descEn: "143 settlement water schemes + Dordi lift irrigation; 50% women on local operating committees.",
    statusNe: "बजेटमा प्रस्तावित", statusEn: "Proposed in budget",
    progress: 34,
    tagNe: "पूर्वाधार", tagEn: "Infrastructure",
  },
  {
    id: "climate",
    numNe: "०६", numEn: "06",
    titleNe: "जलवायु अनुकूलन कोष",
    titleEn: "Climate Adaptation Fund",
    descNe: "हिमनदी उद्गम जोखिम, पहिरो र खडेरीका लागि प्रदेश–सङ्घ संयुक्त कोष। प्यारिस सम्झौता धारा ६ जोडिने।",
    descEn: "Joint federal-provincial fund for GLOF, landslide & drought risk, linked to Paris Art. 6 finance.",
    statusNe: "अवधारणा पत्र", statusEn: "Concept note",
    progress: 12,
    tagNe: "जलवायु", tagEn: "Climate",
  },
];
