import type { Project } from "@/lib/types";

export const PROJECTS: Project[] = [
  {
    id: "P-2082-041",
    cat: "hydro", palika: "dordi",
    titleNe: "दोर्दी खोला लघु जलविद्युत्, चरण–२ (२२ मेगावाट)",
    titleEn: "Dordi Khola Small Hydro, Phase 2 (22 MW)",
    status: "ongoing", progress: 64,
    budgetNe: "रु. ३.२ अर्ब", budgetEn: "NPR 3.2 B",
    startNe: "२०८० असार", startEn: "Jun 2023",
    etaNe: "२०८३ असोज", etaEn: "Sep 2026",
    updateNe: "पेनस्टक पाइप बिछ्याउने काम ७८% सम्पन्न; टर्बाइन स्थापना जेठमा सुरु।",
    updateEn: "Penstock laying 78% complete; turbine installation to begin in May.",
    updatedNe: "२ दिन अघि", updatedEn: "2 days ago",
    tagsNe: ["स्थानीय सेयर ५१%", "रोजगारी ४७०"], tagsEn: ["51% local equity", "470 jobs"],
    img: "Dordi intake site",
  },
  {
    id: "P-2082-038",
    cat: "road", palika: "marsyangdi",
    titleNe: "बेसीशहर–खुदी कालोपत्रे (२८.४ किमी)",
    titleEn: "Besisahar–Khudi Blacktop (28.4 km)",
    status: "ongoing", progress: 42,
    budgetNe: "रु. १.४ अर्ब", budgetEn: "NPR 1.4 B",
    startNe: "२०८१ कार्तिक", startEn: "Nov 2024",
    etaNe: "२०८३ वैशाख", etaEn: "Apr 2026",
    updateNe: "१२ किमी कालोपत्रे सकियो; दुई पहिरो जोखिम क्षेत्रमा रिटेनिङ वाल निर्माण।",
    updateEn: "12 km blacktopped; retaining walls underway at two landslide-prone sections.",
    updatedNe: "४ दिन अघि", updatedEn: "4 days ago",
    tagsNe: ["अन्नपूर्ण सर्किट", "सबै मौसम"], tagsEn: ["Annapurna Circuit", "All-weather"],
    img: "Blacktop section, Bhulbhule",
  },
  {
    id: "P-2082-037",
    cat: "agri", palika: "madhyanepal",
    titleNe: "मध्यनेपाल कफी क्लस्टर — साझा प्रशोधन केन्द्र",
    titleEn: "Madhya Nepal Coffee Cluster — Common Processing Unit",
    status: "ongoing", progress: 71,
    budgetNe: "रु. १८ करोड", budgetEn: "NPR 180 M",
    startNe: "२०८१ माघ", startEn: "Feb 2025",
    etaNe: "२०८३ जेठ", etaEn: "May 2026",
    updateNe: "भवन ८२% सम्पन्न; वाशिङ स्टेसन इटालीबाट आयात हुने क्रममा।",
    updateEn: "Building 82% done; washing station en-route from Italy.",
    updatedNe: "१ हप्ता अघि", updatedEn: "1 week ago",
    tagsNe: ["३,२०० कृषक", "जैविक प्रमाणीकरण"], tagsEn: ["3,200 farmers", "Organic cert"],
    img: "Coffee processing unit",
  },
  {
    id: "P-2082-033",
    cat: "tour", palika: "kwholasothar",
    titleNe: "घले गाउँ–घनपोखरा पदमार्ग स्तरोन्नति",
    titleEn: "Ghalegaun–Ghanpokhara trail upgrade",
    status: "ongoing", progress: 58,
    budgetNe: "रु. ९.२ करोड", budgetEn: "NPR 92 M",
    startNe: "२०८१ मंसिर", startEn: "Dec 2024",
    etaNe: "२०८३ चैत", etaEn: "Mar 2026",
    updateNe: "४.१ किमी ढुङ्गा–छाप मार्ग सकियो; ८ वटा दृश्य विश्राम स्थल निर्माण।",
    updateEn: "4.1 km stone path done; 8 scenic waypoints being built.",
    updatedNe: "३ दिन अघि", updatedEn: "3 days ago",
    tagsNe: ["होमस्टे २४७", "गुरुङ संस्कृति"], tagsEn: ["247 homestays", "Gurung culture"],
    img: "Ghalegaun viewpoint",
  },
  {
    id: "P-2082-029",
    cat: "water", palika: "rainas",
    titleNe: "राइनास–सुन्दरबजार खानेपानी सञ्जाल",
    titleEn: "Rainas–Sundarbazar Water Grid",
    status: "tender",
    budgetNe: "रु. ८४ करोड", budgetEn: "NPR 840 M",
    startNe: "२०८३ असार अपेक्षित", startEn: "Jun 2026 expected",
    etaNe: "२०८५ माघ", etaEn: "Feb 2028",
    updateNe: "DPR स्वीकृत; टेन्डर आह्वान तयारीमा, बोलपत्र आउने साता खुल्ने।",
    updateEn: "DPR approved; tender opening scheduled next week.",
    updatedNe: "५ दिन अघि", updatedEn: "5 days ago",
    tagsNe: ["२६ बस्ती", "१८,४०० लाभग्राही"], tagsEn: ["26 settlements", "18,400 beneficiaries"],
    img: "Spring source, Rainas",
  },
  {
    id: "P-2082-024",
    cat: "water", palika: "dordi",
    titleNe: "दोर्दी उठान सिँचाइ, पाइलट चरण",
    titleEn: "Dordi Lift Irrigation — Pilot Phase",
    status: "completed", progress: 100,
    budgetNe: "रु. ४२ करोड", budgetEn: "NPR 420 M",
    startNe: "२०७९ असोज", startEn: "Oct 2022",
    etaNe: "२०८२ पुस सम्पन्न", etaEn: "Completed Jan 2026",
    updateNe: "पाइलट सफल; २,१०० घरधुरीलाई सिँचाइ उपलब्ध। चरण–२ स्वीकृतिको तयारी।",
    updateEn: "Pilot successful; 2,100 households now served. Phase-2 approval drafted.",
    updatedNe: "१ महिना अघि", updatedEn: "1 month ago",
    tagsNe: ["२,१०० घरधुरी", "१८५ हेक्टर"], tagsEn: ["2,100 households", "185 ha"],
    img: "Dordi pump station",
  },
  {
    id: "P-2082-018",
    cat: "digital", palika: "besisahar",
    titleNe: "बेसीशहर फाइबर ब्याकबोन (पाइलट)",
    titleEn: "Besisahar Fibre Backbone (Pilot)",
    status: "completed", progress: 100,
    budgetNe: "रु. ११ करोड", budgetEn: "NPR 110 M",
    startNe: "२०८१ भदौ", startEn: "Aug 2024",
    etaNe: "२०८२ माघ सम्पन्न", etaEn: "Completed Jan 2026",
    updateNe: "सबै ११ वडामा फाइबर पुग्यो; पालिका डाटा सेन्टर सञ्चालनमा।",
    updateEn: "Fibre now reaches all 11 wards; palika data centre live.",
    updatedNe: "३ हप्ता अघि", updatedEn: "3 weeks ago",
    tagsNe: ["११ वडा", "२ Gbps"], tagsEn: ["11 wards", "2 Gbps"],
    img: "Data centre, Besisahar",
  },
  {
    id: "P-2082-015",
    cat: "road", palika: "dudhpokhari",
    titleNe: "दूधपोखरी पहिरो पुनर्स्थापना, साम्रुङ खण्ड",
    titleEn: "Dudhpokhari landslide rehab, Samrung stretch",
    status: "delayed",
    budgetNe: "रु. २७ करोड", budgetEn: "NPR 270 M",
    startNe: "२०८१ असार", startEn: "Jun 2024",
    etaNe: "२०८२ फागुन → २०८३ असार", etaEn: "Rebased to Jun 2026",
    updateNe: "बर्खाले अतिरिक्त क्षति; बजेट पुनर्समायोजन प्रस्ताव समितिमा।",
    updateEn: "Monsoon caused additional damage; budget revision tabled in committee.",
    updatedNe: "२ हप्ता अघि", updatedEn: "2 weeks ago",
    tagsNe: ["२.३ किमी", "जोखिम मध्यम"], tagsEn: ["2.3 km", "Risk: medium"],
    img: "Samrung slip zone",
  },
  {
    id: "P-2082-012",
    cat: "hydro", palika: "marsyangdi",
    titleNe: "पैयुँखोला ८.४ मेगावाट — सामुदायिक जलविद्युत्",
    titleEn: "Paiyunkhola 8.4 MW — Community Hydro",
    status: "dpr",
    budgetNe: "रु. १.८ अर्ब", budgetEn: "NPR 1.8 B",
    startNe: "२०८३ कार्तिक अपेक्षित", startEn: "Nov 2026 expected",
    etaNe: "२०८६ जेठ", etaEn: "May 2029",
    updateNe: "विस्तृत परियोजना प्रतिवेदन अन्तिम चरणमा; सामुदायिक सेयर ३०% आरक्षित।",
    updateEn: "DPR in final review; 30% community equity reserved.",
    updatedNe: "१ हप्ता अघि", updatedEn: "1 week ago",
    tagsNe: ["सामुदायिक ३०%", "रन अफ रिभर"], tagsEn: ["30% community", "Run-of-river"],
    img: "Paiyun river survey",
  },
  {
    id: "P-2082-009",
    cat: "edu", palika: "sundarbazar",
    titleNe: "सुन्दरबजार प्राविधिक शिक्षालय — नयाँ भवन",
    titleEn: "Sundarbazar Technical School — New Block",
    status: "ongoing", progress: 35,
    budgetNe: "रु. १२ करोड", budgetEn: "NPR 120 M",
    startNe: "२०८१ फागुन", startEn: "Feb 2025",
    etaNe: "२०८३ माघ", etaEn: "Jan 2027",
    updateNe: "जग र ग्राउन्ड फ्लोर सकियो; इलेक्ट्रिकल ट्रेडका लागि उपकरण खरीद प्रक्रियामा।",
    updateEn: "Foundation and ground floor done; electrical trade equipment being procured.",
    updatedNe: "१० दिन अघि", updatedEn: "10 days ago",
    tagsNe: ["४८० विद्यार्थी", "६ ट्रेड"], tagsEn: ["480 students", "6 trades"],
    img: "Construction site",
  },
  {
    id: "P-2082-006",
    cat: "tour", palika: "marsyangdi",
    titleNe: "अन्नपूर्ण बेस क्याम्प मार्ग — सूचना बोर्ड",
    titleEn: "Annapurna trail signage — digital boards",
    status: "completed", progress: 100,
    budgetNe: "रु. ३.४ करोड", budgetEn: "NPR 34 M",
    startNe: "२०८१ कार्तिक", startEn: "Nov 2024",
    etaNe: "२०८२ माघ सम्पन्न", etaEn: "Completed Jan 2026",
    updateNe: "सबै ३८ सूचना बोर्ड जडान; NE/EN/CN त्रिभाषिक। सौर्य सञ्चालित।",
    updateEn: "All 38 boards installed; trilingual NE/EN/CN, solar-powered.",
    updatedNe: "३ हप्ता अघि", updatedEn: "3 weeks ago",
    tagsNe: ["३८ बोर्ड", "सौर्य"], tagsEn: ["38 boards", "Solar"],
    img: "Trail signage",
  },
  {
    id: "P-2082-003",
    cat: "agri", palika: "kwholasothar",
    titleNe: "क्व्होलासोथार जडिबुटी प्रशोधन केन्द्र",
    titleEn: "Kwholasothar herb processing centre",
    status: "concept",
    budgetNe: "रु. ८ करोड (अनुमानित)", budgetEn: "NPR 80 M (est)",
    startNe: "२०८३ असोज अपेक्षित", startEn: "Sep 2026 expected",
    etaNe: "२०८४ जेठ", etaEn: "May 2027",
    updateNe: "सम्भाव्यता अध्ययन सुरु — जटामसी, चिराइतो, यार्सागुम्बा बजार विश्लेषण।",
    updateEn: "Feasibility study started — jatamansi, chiraito, yarsagumba market analysis.",
    updatedNe: "२ हप्ता अघि", updatedEn: "2 weeks ago",
    tagsNe: ["१,८०० संकलक", "उच्च मूल्य"], tagsEn: ["1,800 collectors", "High value"],
    img: "Himalayan herbs",
  },
];
